package org.example.foodypet.domain.pet.entity;

public enum CatBreed {
    MIX, KOREAN_SHORTHAIR, RUSSIAN_BLUE, PERSIAN, SIAMESE, SCOTTISH_FOLD, MUNCHKIN, BRITISH_SHORTHAIR, AMERICAN_SHORTHAIR, BENGAL, MAINE_COON, RAGDOLL, TURKISH_ANGORA
}
